apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
 name: vault-james-secret
spec:
 provider: vault
 parameters:
   roleName: "csi"
   vaultAddress: "http://vault.vault:8200"
   objects: |
     - objectName: "secret"
       secretPath: "secret/data/james-secret"
       secretKey: "secret"