{{- if .Values.sealedSecrets.create -}}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .Values.secrets.nameOverride | default (include "balrog.fullname" .) }}
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  labels:
    {{- include "balrog.labels" . | nindent 4 }}
spec:
  encryptedData:
    secret: {{ .Values.sealedSecrets.jamesSecret }}
  template:
    metadata:
      name: {{ .Values.secrets.nameOverride | default (include "balrog.fullname" .) }}
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      labels:
        {{- include "balrog.labels" . | nindent 8 }}
{{- end }}
