{{- if .Values.secrets.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "balrog.fullname" . }}
  labels:
    {{- include "balrog.labels" . | nindent 4 }}
data:
  secret: {{ .Values.secrets.supersecret | b64enc }}

{{- end }}