{{- if .Values.secrets.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.nameOverride | default (include "balrog.fullname" .) }}
  labels:
    {{- include "balrog.labels" . | nindent 4 }}
  {{- with .Values.secrets.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  secret: {{ .Values.secrets.supersecret | b64enc }}

{{- end }}
