{{- if .Values.secretsStore.create -}}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: vault-james-secret
  labels:
    {{- include "balrog.labels" . | nindent 4 }}
spec:
 provider: vault
 parameters:
   roleName: csi
   vaultAddress: {{ .Values.secretsStore.vaultAddress }}
   objects: |
     - objectName: {{ .Values.secretsStore.objectName }}
       secretPath: {{ .Values.secretsStore.secretPath }}
       secretKey: {{ .Values.secretsStore.secretKey }}
{{- end }}