# base
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
generatorOptions:
  disableNameSuffixHash: true
resources:
- deployment.yml
- svc.yml
- ingress.yml
labels:
- includeSelectors: true
  pairs:
    app: kustomize
    version: demo02
