---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: hello
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: hello
          # FIXME (version à déployer)
          image: registry.gitlab.com/gitops-heros/sith:0.1
          env:
          - name: ENV
            value: "secret"
          volumeMounts:
          - name: secret-volume
            mountPath: "/etc/sith/"
            readOnly: true
      volumes:
        - name: secret-volume
          secret:
            secretName: james-secrets

