apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: james-secrets
spec:
  encryptedData:
    secret: AgAjgasC576bLztBZ1/DQA6E7nMtNNRIoBeNqgZ/0VGFcG5StqTmjYzq+6gzVrJtEwKz8ZDVSbTwNK8Gz9MnB2y8QQbN4FF0M4s4pfli+cXP8IZ4efICufo1+nua8h0dKfRPmT7vFKv3y3quOx8+yiGJkPGVNbTUesCXdkbobaszPeOggAtkTXriqMFF+pTkuSHo++7s3vAr0vTJrGKQZX2j9IZizF8FEysf37zEaeiThLotWb42Dpi0nYQvZtxNFgy9m8/h6yN6IMAuOJBsGsDVzVwybl2whHd6DxTHRnZDaguYnrasLdB5s2Yqv4IlBZ6SUP4UpGX6yHFU6rQ7PQbOYbEZwLHAOek7fm8hIWugt1xlYUTSXXEI6Bm/XFckIm98BscDaZOndh4A8a8V8+/rb7hBEz2i/fC0I07YnuW4OO+prPKa+wbbVF54XlnureulvewbqqM+b6Yp1TbtYyEidXWEdENdlrvD6y5O/Bsqnb5AVl7Fi/uda6ayg4/i0cxZ8yaddLmeYPAD76VF//vxVQu4Orqh9ciHgffqqbGx9RfCEJX+qybIy0HwjInlxDgwcqrfONlvNEF1ZsytKJsbvKm0U2GwUWWJ+QwO5kqm4GJ2PSUYjeln0P1MNZJlRrhPjh6NLwha9QRNJM4XOpOQlNDQNvUzjys4B2s0DbS1I+zG8kTlG9xWbWZxSj2JesVkXziJj7ICiaMykmfFNnGa
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: james-secrets

