# overlay staging
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- secrets-store.yml
- ../../base
patches:
- path: secrets-store.yml
- path: deployment.yml
- path: ingress.yml
